spring:
  application:
    name: pokedex-capas-012026

  datasource:
    url: jdbc:postgresql://localhost:5432/pokedex
    password: root
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: luisa
      password: root