CREATE TABLE pokemon
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    type     VARCHAR(255),
    level    INTEGER,
    weakness VARCHAR(255),
    CONSTRAINT pk_pokemon PRIMARY KEY (id)
);

CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE trainer
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    age  INTEGER,
    CONSTRAINT pk_trainer PRIMARY KEY (id)
);

CREATE TABLE trainer_pokemon
(
    pokemon_id INTEGER NOT NULL,
    trainer_id INTEGER NOT NULL
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255),
    password   VARCHAR(255),
    trainer_id INTEGER,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_trainer UNIQUE (trainer_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_TRAINER FOREIGN KEY (trainer_id) REFERENCES trainer (id);

ALTER TABLE trainer_pokemon
    ADD CONSTRAINT fk_trapok_on_pokemon FOREIGN KEY (pokemon_id) REFERENCES pokemon (id);

ALTER TABLE trainer_pokemon
    ADD CONSTRAINT fk_trapok_on_trainer FOREIGN KEY (trainer_id) REFERENCES trainer (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);